site_name: ACTEDU Docs
site_url: https://inglan2.github.io/ACTEDUDocs
theme:
  name: material
  palette: 

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.tabs
    - navigation.indexes 
    - navigation.top
    - navigation.instant
    - navigation.instant.progress


nav:
  - Home: index.md
  - Unblocked Sites:
    - Gmae Sites: unblocked-sites/gmae-sites.md
    - Hosted Services: unblocked-sites/hosted-services.md
  - Guides:
    - Guides: guides/index.md
  - Exploits:
    - Exploits: exploits/index.md
  - Other: other.md